apiVersion: v1
kind: Service
metadata:
  name: mediawiki-db-srvice
  labels:
    app: mediawiki-db
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mediawiki-db
